//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20201129081.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public string ogrId { get; set; }
        public string ogrNo { get; set; }
        public string ogrAdSoyad { get; set; }
        public string ogrMail { get; set; }
        public int ogrYas { get; set; }
        public string ogrDgYer { get; set; }
        public int uyeadmin { get; set; }
        public string ogrSifre { get; set; }
        public string KullaniciAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
